# Generated by Django 5.1.1 on 2024-10-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.note'),
        ),
    ]
